### ISSUE TITLE
Many unique lines with spaces or non-ASCII characters being deleted

### ISSUE THREAD

**Issue by tinyapps** [nil0x42/duplicut#11]
Thanks so much for crafting and sharing duplicut.

It appears to delete many unique lines containing spaces or non-ASCII characters, e.g.,

```
$ cat 1

foo
bar
pass with spaces
a pass word
another unique password

$ duplicut 1 -o 1.out

$ cat 1.out

foo
bar
a pass word
```

Any line with 5 or more Japanese characters is cut:

```
$ cat 2

一
十一
百十一
千百十一
万千百十一
ほげふがぴよ

$ duplicut 2 -o 2.out

$ cat 2.out

一
十一
百十一
千百十一
```

**Comment by nil0x42** [comment]
Hi ! I guess you ran duplicut without changing the options.
A said by `duplicut --help`, the `--line-max-size` option's default value is **14**.
This behavior can be discussed, but at the time i implemented it because duplicut was meant to optimize password wordlists, and i rarely want >14 chars passwords in my lists. This allows filtering garbage lines from wordlists downloaded in the internet, that comonly contain long useless html lines or irrelevant lines due to parsing errors.

Also, the empty lines deletion is hardcoded, because the goal is to speedup tools like hascat & john, so they don't have to read empty lines (or guess empty passwords)

Anyway, a limitation of --line-max-size is 254, because line_sz is stored in 8bits in the hashmap (for memory optimization) 

Please close the issue if my comment resolved it, and thank you for the feedback !

**Comment by tinyapps** [comment]
Sorry to have missed that, nil0x42 - thanks so much for letting me know!
