### ISSUE TITLE
Transform lines to lowercase

### ISSUE THREAD

**Issue by eddie4** [nil0x42/duplicut#23]
Using wordlists typically are used with transform rules. Personally I would like a option to transform all lines to lowercase.

Perhaps additionally even a option to strip [0-9] and specials characters.

**Comment by nil0x42** [comment]
Hi ! For transform rules, i'm a big fan o piping multiple shell commands.
I initially made duplicut because removing duplicates from a very large wordlist without sorting was not feasible otherwise.

Other actions, such as lowering, or stripping numbers can easily be achieved with built-in linux commands.
Take a look at my [nil0x42/cracking-utils](https://github.com/nil0x42/cracking-utils). Here i have some simple scripts i like to use for creting my wordlists.
Lowering whole wordlist is also an easy task with `tr`:
```shell
tr '[:upper:]' '[:lower:]' < "old.txt" > "new.txt"
```

Duplicut is a tool you should use as a last step during wordlist creation. After concatenating multiple sources as you wish, in your prefered order, then you can `duplicut` it to remove duplicates, as quickly as possible, without losing your precious order.

-------------

Anyway, even if main focus is dedupe, i still implemented `--line-max-size` & `--printable` filters, because they are only filters, and no transformers. They just are additional conditions to decide if a line should be added or not.

If you have suggestions for adding relevant filters, i can consider implementing (if the overhead is low).

Thank you for posting this issue !

**Comment by nil0x42** [comment]
EDIT: after taking 1 minute to test adding a tolower() between buffer read/write cycle on first copy, it looks like it has almost no overhead, so i'm adding it as TODO for next release :+1: 

What do you think would be good single letter options for `--tolower` and `--toupper` ? I'm thinking of `-x`/`-X`, or perhaps `-c`/`-C`, because `-l` is already taken by `--line-max-size`.

Opinions are welcome !

**Comment by eddie4** [comment]
Personally I would say -c/-C would make the most sense.
