### ISSUE TITLE
Output to stdout by default

### ISSUE THREAD

**Issue by SomeKirill** [nil0x42/duplicut#32]
It would be a nice feature to output to stdout by default, as ```sort -u``` or ```anew``` do.

**Comment by nil0x42** [comment]
Hi ! The choice to not output to STDOUT by default is because is actually takes more time.
Indeed, duplicut aims to remove duplicates from MASSIVE files while keeping original ordering, even with a small amount of available memory. For that reason, loading the whole file in memory is not an option, so file access and state changes need regular disk access.

The implementation starts copying the input file into dest file, THEN, duplicate removal occurs directly on dest file. And when dest file is set to stdout, duplicut in reality creates a temporary file it uses as dest file, and in the end writes is to stdout before deleting it.

Conclusion, for tools intended to sort small files, and loading everything in memory, such as `sort -u`, it makes total sense to defaultly output to stdout because a lot of use cases don't need persistence. But duplicut is focused on massive, multi GB files, and a common reason to remove duplicates from massive file is to write it in a file.

Resuming, `duplicut IN.TXT -o /dev/stdout > OUT.TXT` is slower than `duplicut -i IN.TXT -o OUT.TXT`, because there is no need for an intermediary temporary file in the second case.

Feel free to ask if you have any question !
Thank you for trying duplicut
